# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pjKlNZ5xVvbiNV1bCueBDgrZeVeIG81
"""

def tijolo(valorA, valorB):
  print("Aqui é o numero:" + str(valorA) + str(valorB))
  resultado = int(valorA) + int(valorB)
  print(resultado)

tijolo(2,5)
tijolo(30,55)

import requests 

def x():
  print('CEPython')

  cep=input("Digite o CEP: ")

  caixinha = requests.get ('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco= caixinha.json()
  #print(endereco)
'''
  print("CEP ENCONTRADO: ")
  print("CEP: " + endereco['cep'])
  print(f"Rua:{ endereco['logradouro']}")
  print("Cidade: {}".format(endereco['localidade']))
  print(f"Estado: {endereco['uf']}")
'''
x()

import requests 

def x():
  print('CEPython')

  cep=input("Digite o CEP: ")

  while len(cep) !=8 :
    print("CEP INVALIDO")
    cep=input("Digite o CEP: ")

  caixa = requests.get ('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco= caixa.json()

  if 'erro' not in endereco:
    print("CEP ENCONTRADO: ")
    print("CEP: " + endereco['cep'])
    print(f"Rua:{ endereco['logradouro']}")
    print("Cidade: {}".format(endereco['localidade']))
    print(f"Estado: {endereco['uf']}")

  else:
    print("CEP INVALIDO")

  print("***********************")

  def validar():
    choice =input("Outra consulta? \n 1- Sim\n 2- Não \n ")
    #\n pular linha
    if choice == "1" or choice == "2" :
      if int(choice) ==1 :
        x()
      else:
        print("TCHAU! ")
    else:
      print("INVALIDO")
      validar()
  validar()
x()